# Generated by Django 2.2 on 2019-04-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='details',
            field=models.TextField(help_text='Details regarding the client', verbose_name='Details'),
        ),
    ]
