# Generated by Django 2.2 on 2019-05-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_add_branch_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Name'),
        ),
    ]
