# Generated by Django 2.2.2 on 2019-08-21 08:31

import core.validators
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_branch_name_not_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='slug',
            field=models.SlugField(allow_unicode=True, editable=False, help_text='A label for URL config.', max_length=120, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-\\w]+\\Z'), "Enter a valid 'slug' consisting of Unicode letters, numbers, underscores, or hyphens.", 'invalid'), core.validators.validate_slug]),
        ),
    ]
