# Generated by Django 2.2.2 on 2019-08-21 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_create_client_slug_in_save_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='client.Client', verbose_name='Client'),
        ),
    ]
