# Generated by Django 2.2.2 on 2019-08-24 14:56

from django.db import migrations, models


def add_default_settlement(apps, schema_editor):
    Branch = apps.get_model('client', 'Branch')

    for branch in Branch.objects.all():
        branch.settlement = 'City 17'
        branch.save()

def remove_default_settlement(apps, schema_editor):
    Branch = apps.get_model('client', 'Branch')

    for branch in Branch.objects.all():
        branch.settlement = None
        branch.save()


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_protect_foregin_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='settlement',
            field=models.CharField(
                null=True,
                blank=True,
                default=None,
                max_length=120,
                verbose_name='Settlement',
            ),
            preserve_default=False,
        ),
        migrations.RunPython(
            add_default_settlement,
            reverse_code=remove_default_settlement,
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('client', 'name', 'settlement', 'address')},
        ),
        migrations.AlterField(
            model_name='branch',
            name='settlement',
            field=models.CharField(
                null=False,
                blank=False,
                default=None,
                max_length=120,
                verbose_name='Settlement',
            ),
            preserve_default=False,
        ),
    ]
