# Generated by Django 2.2.7 on 2019-11-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_add_settlement_to_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='details',
            field=models.TextField(verbose_name='Information'),
        ),
    ]
