# Generated by Django 2.2 on 2019-04-25 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_client_details_textfield'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Client', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['authtor', 'client'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.CharField(max_length=250, verbose_name='Equipment')),
                ('equipment_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Equipment price')),
                ('work', models.CharField(max_length=250, verbose_name='Work')),
                ('work_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Work price')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['equipment', 'work'],
                'unique_together': {('equipment', 'work')},
            },
        ),
        migrations.CreateModel(
            name='OrderOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.Order', verbose_name='Order')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.Service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Order option',
                'verbose_name_plural': 'Order options',
                'unique_together': {('order', 'service')},
            },
        ),
    ]
