# Generated by Django 2.2 on 2019-04-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_add_created_and_modified_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='services',
            field=models.ManyToManyField(related_name='orders', through='calc.OrderOption', to='calc.Service', verbose_name='Services'),
        ),
    ]
