# Generated by Django 2.2 on 2019-05-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_order_add_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='rating',
            field=models.PositiveIntegerField(default=0, verbose_name='Rating'),
        ),
    ]
