# Generated by Django 2.2 on 2019-05-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_add_service_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderoption',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
    ]
