# Generated by Django 2.2 on 2019-05-10 08:52

from django.db import migrations, models
import django.db.models.deletion


default_branch_name = 'migration_calc_0009'
default_branch_address = """This branch created due to
calc/migrations/0009_add_branch_to_order
migration please input correct data"""


def add_branch_data(apps, schema_editor):
    Order = apps.get_model('calc', 'Order')
    Branch = apps.get_model('client', 'Branch')

    orders = Order.objects.all()
    for order in orders:
        branch, _ = Branch.objects.get_or_create(
            client=order.client,
            name=default_branch_name,
            address=default_branch_address,
        )
        order.branch = branch
        order.save()

def delete_branch_data(apps, schema_editor):
    Branch = apps.get_model('client', 'Branch')
    branches = Branch.objects.filter(
        name=default_branch_name,
        address=default_branch_address
    )
    if branches:
        branches.delete()
    Order = apps.get_model('calc', 'Order')
    Order.objects.update(branch=None)


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_branch_name_not_unique'),
        ('calc', '0008_order_option_set_default_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(
                blank=True,
                null=True,
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='orders',
                to='client.Branch',
                verbose_name='Branch'),
        ),
        migrations.RunPython(
            add_branch_data,
            reverse_code=delete_branch_data,
        ),
        migrations.AlterField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(
                blank=False,
                null=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='orders',
                to='client.Branch',
                verbose_name='Branch'),
        ),
    ]
