# Generated by Django 2.2 on 2019-05-18 14:00

from django.db import migrations, models


def add_price(apps, schema_editor):
    Service = apps.get_model('calc', 'Service')

    for service in Service.objects.all():
        service.price = service.equipment_price + service.work_price
        service.save()

def delete_price(apps, schema_editor):
    Service = apps.get_model('calc', 'Service')
    Service.objects.update(price=0)


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0009_add_branch_to_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.DecimalField(
                null=False,
                blank=False,
                decimal_places=2,
                default=0,
                editable=False,
                max_digits=9,
                verbose_name='Price',
            ),
        ),
        migrations.RunPython(
            add_price,
            reverse_code=delete_price,
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(
                null=False,
                blank=False,
                decimal_places=2,
                editable=False,
                max_digits=9,
                verbose_name='Price',
            ),
        ),
    ]
