# Generated by Django 2.2 on 2019-05-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0010_add_price_field_to_service_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=9, verbose_name='Total'),
        ),
    ]
