# Generated by Django 2.2.2 on 2019-08-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0012_protect_foregin_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderoption',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=9, verbose_name='Total price'),
        ),
        migrations.AddField(
            model_name='orderoption',
            name='service_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=9, verbose_name='Service price'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=9, verbose_name='Total price'),
        ),
        migrations.AlterField(
            model_name='service',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Rating'),
        ),
    ]
