# Generated by Django 2.2.2 on 2019-08-24 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0013_add_service_price_and_price_to_orderoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderoption',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='options', to='calc.Service', verbose_name='Option'),
        ),
        migrations.AlterField(
            model_name='orderoption',
            name='service_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=9, verbose_name='Option price'),
        ),
    ]
