# Generated by Django 2.2.2 on 2019-08-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0014_change_order_option_verbose_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='services',
            field=models.ManyToManyField(related_name='orders', through='calc.OrderOption', to='calc.Service', verbose_name='Options'),
        ),
    ]
