# Generated by Django 2.2.2 on 2019-08-25 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0015_change_order_verbose_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderoption',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='calc.Order', verbose_name='Order'),
        ),
    ]
