# Generated by Django 2.2.7 on 2019-11-16 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0016_allow_delete_orders_with_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['author', 'client'], 'verbose_name': 'Estimate', 'verbose_name_plural': 'Estimates'},
        ),
        migrations.AlterModelOptions(
            name='orderoption',
            options={'verbose_name': 'Estimate equipment', 'verbose_name_plural': 'Estimates equipment'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['equipment', 'work'], 'verbose_name': 'Equipment', 'verbose_name_plural': 'Equipment'},
        ),
        migrations.AlterField(
            model_name='order',
            name='services',
            field=models.ManyToManyField(related_name='orders', through='calc.OrderOption', to='calc.Service', verbose_name='Equipment'),
        ),
        migrations.AlterField(
            model_name='orderoption',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='calc.Order', verbose_name='Estimate'),
        ),
        migrations.AlterField(
            model_name='orderoption',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='options', to='calc.Service', verbose_name='Equipment'),
        ),
        migrations.AlterField(
            model_name='orderoption',
            name='service_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=9, verbose_name='Equipment price'),
        ),
    ]
