# Generated by Django 3.1.7 on 2021-04-06 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0020_add_timedelta_field_to_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderoption',
            name='work_duration',
            field=models.DurationField(default=datetime.timedelta(0), editable=False, help_text='Duration time format [HH:]MM', verbose_name='Work duration'),
        ),
        migrations.AlterField(
            model_name='service',
            name='work_duration',
            field=models.DurationField(default=datetime.timedelta(0), help_text='Duration time format [HH:]MM', verbose_name='Work duration'),
        ),
    ]
